/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests/string.check" instead.
 */

#include <check.h>
#include <stdio.h>
#include <string.h>

#include "s21_string.h"

START_TEST(memchr_test) {
  char t_1[] = "1234567";
  char t_2[] = "\twqrwert";
  char t_3[] = "Hello!\n";
  char t_4[] = "DigitaWLLich";
  int t_5 = '3';
  int t_6 = '7';
  int t_7 = '\n';
  int t_8 = 'w';
  int t_9 = '0';

  ck_assert_uint_eq((unsigned long)s21_memchr(t_1, t_5, 8),
                    (unsigned long)memchr(t_1, t_5, 8));
  ck_assert_uint_eq((unsigned long)s21_memchr(t_2, t_6, 6),
                    (unsigned long)memchr(t_2, t_6, 6));
  ck_assert_uint_eq((unsigned long)s21_memchr(t_3, t_7, 1),
                    (unsigned long)memchr(t_3, t_7, 1));
  ck_assert_uint_eq((unsigned long)s21_memchr(t_4, t_8, 4),
                    (unsigned long)memchr(t_4, t_8, 4));
  ck_assert_uint_eq((unsigned long)s21_memchr(t_1, t_9, 2),
                    (unsigned long)memchr(t_1, t_9, 2));
  ck_assert_uint_eq((unsigned long)s21_memchr(t_2, t_5, 3),
                    (unsigned long)memchr(t_2, t_5, 3));
  ck_assert_uint_eq((unsigned long)s21_memchr(t_3, t_6, 7),
                    (unsigned long)memchr(t_3, t_6, 7));
  ck_assert_uint_eq((unsigned long)s21_memchr(t_4, t_7, 6),
                    (unsigned long)memchr(t_4, t_7, 6));
  ck_assert_uint_eq((unsigned long)s21_memchr(t_1, t_8, 8),
                    (unsigned long)memchr(t_1, t_8, 8));
}
END_TEST

START_TEST(memcmp_test) {
  char t_1[] = "!@#123321312!#@";
  char t_2[] = "Helli-ku";
  char t_3[] = "MEAOU";
  char t_4[] = "\n\t\0";
  char t_5[] = "\0";
  char t_6[] = "uppi";
  char t_7[0] = "";

  ck_assert_uint_eq(s21_memcmp(t_1, t_2, 8) < 0, memcmp(t_1, t_2, 8) < 0);
  ck_assert_uint_eq(s21_memcmp(t_2, t_3, 5) < 0, memcmp(t_2, t_3, 5) < 0);
  ck_assert_uint_eq(s21_memcmp(t_3, t_4, 3) < 0, memcmp(t_3, t_4, 3) < 0);
  ck_assert_uint_eq(s21_memcmp(t_4, t_5, 1) < 0, memcmp(t_4, t_5, 1) < 0);

  ck_assert_uint_eq(s21_memcmp(t_7, t_6, 4) < 0, memcmp(t_7, t_6, 1) < 0);
  ck_assert_uint_eq(s21_memcmp(t_5, t_7, 1) < 0, memcmp(t_5, t_7, 1) < 0);
}
END_TEST

START_TEST(memcpy_test) {
  char t_1[] = "123456";
  char t_2[10] = {0};
  char t_3[] = "111 ";
  char t_4[8] = " 111";
  char t_5[] = "qwerty";
  char t_6[] = "\0";

  ck_assert_str_eq(s21_memcpy(t_2, t_1, 6), memcpy(t_2, t_1, 6));
  ck_assert_str_eq(s21_memcpy(t_2, t_4, 6), memcpy(t_2, t_4, 6));
  ck_assert_str_eq(s21_memcpy(t_2, t_3, 4), memcpy(t_2, t_3, 4));
  ck_assert_str_eq(s21_memcpy(t_2, t_5, 6), memcpy(t_2, t_5, 6));
  ck_assert_str_eq(s21_memcpy(t_2, t_6, 1), memcpy(t_2, t_6, 1));
}
END_TEST

START_TEST(memset_test) {
  unsigned char t_1[10] = "1234567890";
  unsigned char t_2[10] = "Hello";

  ck_assert_uint_eq((unsigned long)s21_memset(t_1, '6', 10),
                    (unsigned long)memset(t_1, '6', 10));
  ck_assert_uint_eq((unsigned long)s21_memset(t_1, '2', 10),
                    (unsigned long)memset(t_1, '2', 10));
  ck_assert_uint_eq((unsigned long)s21_memset(t_1, '0', 1),
                    (unsigned long)memset(t_1, '0', 1));
  ck_assert_uint_eq((unsigned long)s21_memset(t_1, '/', 6),
                    (unsigned long)memset(t_1, '/', 6));
  ck_assert_uint_eq((unsigned long)s21_memset(t_2, '4', 4),
                    (unsigned long)memset(t_2, '4', 4));
}
END_TEST

START_TEST(strncat_test) {
  char t_1[4] = "<<<\0";
  char t_2[2] = "5\0";
  char t_3[2] = "5\0";
  char t_4[] = "\0";

  ck_assert_str_eq(s21_strncat(t_1, t_2, 1), "<<<5\0");
  ck_assert_str_eq(s21_strncat(t_3, t_4, 0), strncat(t_2, t_4, 0));
}
END_TEST

START_TEST(strchr_test) {
  char str1[] = "Abcdefg";
  char str2[] = "Abcdefg";

  int symbol1 = 'd';
  int symbol2 = 'd';

  char *ach1 = s21_strchr(str1, symbol1);
  char *ach2 = strchr(str2, symbol2);

  ck_assert_str_eq(ach1, "defg");
  ck_assert_str_eq(ach1, ach2);
  ck_assert_str_eq(str1, str2);
}
END_TEST

START_TEST(strncmp_test) {
  char t_1[] = "Hello World 1";
  char t_2[] = "Hella Worda 2";

  ck_assert_int_eq(s21_strncmp(t_1, t_2, 13) < 0, strncmp(t_1, t_2, 13) < 0);
  ck_assert_int_eq(s21_strncmp(t_1, t_2, 4) == 0, strncmp(t_1, t_2, 4) == 0);
}
END_TEST

START_TEST(strncpy_test) {
  char src[] = "\0";
  char res[] = "\0";
  char exp[] = "\0";
  char src1[] = "123\0";
  char res1[] = "123\0";
  char exp1[] = "123\0";
  char src2[] = "13\0";
  char res2[] = "13\0";
  char exp2[] = "13\0";

  s21_size_t n_byte = 0;
  s21_size_t n1_byte = 0;
  s21_size_t n2_byte = 4;

  s21_strncpy(res, src, n_byte);
  s21_strncpy(res1, src1, n1_byte);
  s21_strncpy(res2, src2, n2_byte);

  strncpy(exp, src, n_byte);
  strncpy(exp1, src1, n1_byte);
  strncpy(exp2, src2, n2_byte);

  ck_assert_str_eq(res, exp);
  ck_assert_str_eq(res1, exp1);
  ck_assert_str_eq(res2, exp2);
}
END_TEST

START_TEST(strcspn_test) {
  char t_1[] = "12314241";
  char t_2[] = "fffff";
  char t_3[] = "//\0\n";
  char t_4[] = "goga";
  char t_5[] = "22222111111111";
  char t_6[] = "22222111111111";

  ck_assert_uint_eq(s21_strcspn(t_1, t_2), strcspn(t_1, t_2));
  ck_assert_uint_eq(s21_strcspn(t_2, t_3), strcspn(t_2, t_3));
  ck_assert_uint_eq(s21_strcspn(t_4, t_3), strcspn(t_4, t_3));
  ck_assert_uint_eq(s21_strcspn(t_5, t_4), strcspn(t_5, t_4));
  ck_assert_uint_eq(s21_strcspn(t_5, t_6), strcspn(t_5, t_6));
}
END_TEST

START_TEST(strlen_test) {
  char t_1[] = "12312\0";
  char t_2[] = "//\0\n\0";
  char t_3[] = "dfdfd11\0";
  char t_4[] = "\0";
  char t_5[] = "\0";
  char t_6[] = "'f'f1213/v/f/////\0";
  char t_7[] = "";
  char t_8[] = " ";
  char t_9[] = "@#$%6&*()\n\t";

  ck_assert_int_eq(s21_strlen(t_1), strlen(t_1));
  ck_assert_int_eq(s21_strlen(t_2), strlen(t_2));
  ck_assert_int_eq(s21_strlen(t_3), strlen(t_3));
  ck_assert_int_eq(s21_strlen(t_4), strlen(t_4));
  ck_assert_int_eq(s21_strlen(t_5), strlen(t_5));
  ck_assert_int_eq(s21_strlen(t_6), strlen(t_6));
  ck_assert_int_eq(s21_strlen(t_7), strlen(t_7));
  ck_assert_int_eq(s21_strlen(t_8), strlen(t_8));
  ck_assert_int_eq(s21_strlen(t_9), strlen(t_9));
}
END_TEST

START_TEST(strpbrk_test) {
  char t_1[] = "01234ffffff";
  char t_2[] = "7773";
  char *str = "Hello, world";
  char *empty = "";

  ck_assert_str_eq(s21_strpbrk(t_1, t_2), "34ffffff");
  ck_assert_str_eq(s21_strpbrk(t_1, t_2), strpbrk(t_1, t_2));

  ck_assert_ptr_eq(s21_strpbrk(str, empty), NULL);
  ck_assert_uint_eq((unsigned long)s21_strpbrk(str, empty),
                    (unsigned long)strpbrk(str, empty));
}
END_TEST

START_TEST(strrchr_test) {
  char t_1[] = "0163456769";
  char t_2[] = ";;;;;;H%%//#HH";
  char t_3[] = " /";

  ck_assert_uint_eq((unsigned long)s21_strrchr(t_1, '6'),
                    (unsigned long)strrchr(t_1, '6'));
  ck_assert_uint_eq((unsigned long)s21_strrchr(t_1, ' '),
                    (unsigned long)strrchr(t_1, ' '));
  ck_assert_uint_eq((unsigned long)s21_strrchr(t_1, '6'),
                    (unsigned long)strrchr(t_1, '6'));
  ck_assert_uint_eq((unsigned long)s21_strrchr(t_2, 'H'),
                    (unsigned long)strrchr(t_2, 'H'));
  ck_assert_uint_eq((unsigned long)s21_strrchr(t_2, '$'),
                    (unsigned long)strrchr(t_2, '$'));
  ck_assert_uint_eq((unsigned long)s21_strrchr(t_2, ';'),
                    (unsigned long)strrchr(t_2, ';'));
  ck_assert_uint_eq((unsigned long)s21_strrchr(t_3, ' '),
                    (unsigned long)strrchr(t_3, ' '));
  ck_assert_str_eq(s21_strrchr(t_2, '\0'), strrchr(t_2, '\0'));
}
END_TEST

START_TEST(strstr_test) {
  char t_1[] = "<<<5>>>";
  char t_2[] = "5";
  char t_3[] = "QwertyQwertyQwerty";
  char t_4[] = "Qwerty";
  char t_5[] = "abcd";
  char t_6[] = "";
  char t_7[] = "aaaaa123aaa1234aaa";
  char t_8[] = "1234";

  ck_assert_ptr_eq(s21_strstr(t_1, t_2), strstr(t_1, t_2));
  ck_assert_ptr_eq(s21_strstr(t_3, t_4), strstr(t_3, t_4));
  ck_assert_ptr_eq(s21_strstr(t_5, t_6), strstr(t_5, t_6));
  ck_assert_ptr_eq(s21_strstr(t_4, t_5), strstr(t_4, t_5));
  ck_assert_ptr_eq(s21_strstr(t_7, t_8), strstr(t_7, t_8));
}
END_TEST

START_TEST(strtok_test) {
  char str_strtok1[] = "one/two/three(four)five";
  char str_strtok2[] = "one/two/three(four)five";
  char str_strtok3[] = " ";
  char str_strtok4[] = " ";
  char str_strtok5[] = "GqwerGqwer";
  char str_strtok6[] = "GqwerGqwer";

  char delim1[] = "/()";
  char delim2[] = "/()";
  char delim3[] = " ";
  char delim4[] = "G";

  char *my_strtok = s21_strtok(str_strtok1, delim1);
  char *origin_strtok = strtok(str_strtok2, delim2);

  char *aish = s21_strtok(str_strtok3, delim3);
  char *orig_aish = strtok(str_strtok4, delim3);
  char *aish1 = s21_strtok(str_strtok5, delim4);
  char *orig_aish1 = strtok(str_strtok6, delim4);

  ck_assert_ptr_eq(aish, orig_aish);
  ck_assert_str_eq(aish1, orig_aish1);

  while (my_strtok != NULL) {
    ck_assert_str_eq(my_strtok, origin_strtok);
    my_strtok = s21_strtok(NULL, delim1);
    origin_strtok = strtok(NULL, delim2);
  }

#include <stdio.h>
#include <string.h>

#include "s21_string.h"
}
END_TEST

START_TEST(sprintf_d_test) {
  char str[80] = {'\0'};
  char str_orig[80] = {'\0'};
  int d = 228;

  int res_1 = s21_sprintf(str, "%10.5d", d);
  int res_1_orig = sprintf(str_orig, "%10.5d", d);
  ck_assert_int_eq(res_1, res_1_orig);
  ck_assert_str_eq(str, str_orig);

  int res_2 = s21_sprintf(str, "% 10.5d", d);
  int res_2_orig = sprintf(str_orig, "% 10.5d", d);
  ck_assert_int_eq(res_2, res_2_orig);
  ck_assert_str_eq(str, str_orig);

  int res_3 = s21_sprintf(str, "%3.5d", d);
  int res_3_orig = sprintf(str_orig, "%3.5d", d);
  ck_assert_int_eq(res_3, res_3_orig);
  ck_assert_str_eq(str, str_orig);

  int res_4 = s21_sprintf(str, "%d", d);
  int res_4_orig = sprintf(str_orig, "%d", d);
  ck_assert_int_eq(res_4, res_4_orig);
  ck_assert_str_eq(str, str_orig);

  int res_5 = s21_sprintf(str, "%0d", d);
  int res_5_orig = sprintf(str_orig, "%0d", d);
  ck_assert_int_eq(res_5, res_5_orig);
  ck_assert_str_eq(str, str_orig);

  int res_6 = s21_sprintf(str, "%-d", d);
  int res_6_orig = sprintf(str_orig, "%-d", d);
  ck_assert_int_eq(res_6, res_6_orig);
  ck_assert_str_eq(str, str_orig);

  int res_7 = s21_sprintf(str, "%+d", d);
  int res_7_orig = sprintf(str_orig, "%+d", d);
  ck_assert_int_eq(res_7, res_7_orig);
  ck_assert_str_eq(str, str_orig);

  int res_8 = s21_sprintf(str, "% d", d);
  int res_8_orig = sprintf(str_orig, "% d", d);
  ck_assert_int_eq(res_8, res_8_orig);
  ck_assert_str_eq(str, str_orig);

  int res_9 = s21_sprintf(str, "%5d", d);
  int res_9_orig = sprintf(str_orig, "%5d", d);
  ck_assert_int_eq(res_9, res_9_orig);
  ck_assert_str_eq(str, str_orig);

  int res_10 = s21_sprintf(str, "%-5d", d);
  int res_10_orig = sprintf(str_orig, "%-5d", d);
  ck_assert_int_eq(res_10, res_10_orig);
  ck_assert_str_eq(str, str_orig);

  int res_11 = s21_sprintf(str, "%+5d", d);
  int res_11_orig = sprintf(str_orig, "%+5d", d);
  ck_assert_int_eq(res_11, res_11_orig);
  ck_assert_str_eq(str, str_orig);

  int res_12 = s21_sprintf(str, "% 5d", d);
  int res_12_orig = sprintf(str_orig, "% 5d", d);
  ck_assert_int_eq(res_12, res_12_orig);
  ck_assert_str_eq(str, str_orig);

  int res_13 = s21_sprintf(str, "%.5d", d);
  int res_13_orig = sprintf(str_orig, "%.5d", d);
  ck_assert_int_eq(res_13, res_13_orig);
  ck_assert_str_eq(str, str_orig);
}
END_TEST

START_TEST(sprintf_c_test) {
  char str[80] = {'\0'};
  char str_orig[80] = {'\0'};
  char A = 'A';

  int res_1 = s21_sprintf(str, "%c", A);
  int res_1_orig = sprintf(str_orig, "%c", A);
  ck_assert_int_eq(res_1, res_1_orig);
  ck_assert_str_eq(str, str_orig);

  str[0] = '\0';
  str_orig[0] = '\0';
  int res_2 = s21_sprintf(str, "%-c", A);
  int res_2_orig = sprintf(str_orig, "%-c", A);
  ck_assert_int_eq(res_2, res_2_orig);
  ck_assert_str_eq(str, str_orig);

  str[0] = '\0';
  str_orig[0] = '\0';
  int res_3 = s21_sprintf(str, "%10c", A);
  int res_3_orig = sprintf(str_orig, "%10c", A);
  ck_assert_int_eq(res_3, res_3_orig);
  ck_assert_str_eq(str, str_orig);

  str[0] = '\0';
  str_orig[0] = '\0';
  int res_4 = s21_sprintf(str, "%-2c", A);
  int res_4_orig = sprintf(str_orig, "%-2c", A);
  ck_assert_int_eq(res_4, res_4_orig);
  ck_assert_str_eq(str, str_orig);
}
END_TEST

START_TEST(sprintf_s_test) {
  char str[80] = {'\0'};
  char str_orig[80] = {'\0'};
  char *A = "Ochko";

  int res_1 = s21_sprintf(str, "%s", A);
  int res_1_orig = sprintf(str_orig, "%s", A);
  ck_assert_int_eq(res_1, res_1_orig);
  ck_assert_str_eq(str, str_orig);

  int res_2 = s21_sprintf(str, "%-s", A);
  int res_2_orig = sprintf(str_orig, "%-s", A);
  ck_assert_int_eq(res_2, res_2_orig);
  ck_assert_str_eq(str, str_orig);

  int res_3 = s21_sprintf(str, "%10s", A);
  int res_3_orig = sprintf(str_orig, "%10s", A);
  ck_assert_int_eq(res_3, res_3_orig);
  ck_assert_str_eq(str, str_orig);

  int res_4 = s21_sprintf(str, "%.5s", A);
  int res_4_orig = sprintf(str_orig, "%.5s", A);
  ck_assert_int_eq(res_4, res_4_orig);
  ck_assert_str_eq(str, str_orig);

  int res_5 = s21_sprintf(str, "%-10s", A);
  int res_5_orig = sprintf(str_orig, "%-10s", A);
  ck_assert_int_eq(res_5, res_5_orig);
  ck_assert_str_eq(str, str_orig);
}
END_TEST

START_TEST(sprintf_ld_test) {
  char str[80] = {'\0'};
  char str_orig[80] = {'\0'};
  long int d = 1504389565748;

  int res_1 = s21_sprintf(str, "%10.5ld", d);
  int res_1_orig = sprintf(str_orig, "%10.5ld", d);
  ck_assert_int_eq(res_1, res_1_orig);
  ck_assert_str_eq(str, str_orig);

  int res_2 = s21_sprintf(str, "% 10.5ld", d);
  int res_2_orig = sprintf(str_orig, "% 10.5ld", d);
  ck_assert_int_eq(res_2, res_2_orig);
  ck_assert_str_eq(str, str_orig);

  int res_3 = s21_sprintf(str, "%3.5ld", d);
  int res_3_orig = sprintf(str_orig, "%3.5ld", d);
  ck_assert_int_eq(res_3, res_3_orig);
  ck_assert_str_eq(str, str_orig);

  int res_4 = s21_sprintf(str, "%ld", d);
  int res_4_orig = sprintf(str_orig, "%ld", d);
  ck_assert_int_eq(res_4, res_4_orig);
  ck_assert_str_eq(str, str_orig);

  int res_5 = s21_sprintf(str, "%-ld", d);
  int res_5_orig = sprintf(str_orig, "%-ld", d);
  ck_assert_int_eq(res_5, res_5_orig);
  ck_assert_str_eq(str, str_orig);

  int res_6 = s21_sprintf(str, "%+ld", d);
  int res_6_orig = sprintf(str_orig, "%+ld", d);
  ck_assert_int_eq(res_6, res_6_orig);
  ck_assert_str_eq(str, str_orig);

  int res_7 = s21_sprintf(str, "% ld", d);
  int res_7_orig = sprintf(str_orig, "% ld", d);
  ck_assert_int_eq(res_7, res_7_orig);
  ck_assert_str_eq(str, str_orig);

  int res_8 = s21_sprintf(str, "%5ld", d);
  int res_8_orig = sprintf(str_orig, "%5ld", d);
  ck_assert_int_eq(res_8, res_8_orig);
  ck_assert_str_eq(str, str_orig);

  int res_9 = s21_sprintf(str, "%-5ld", d);
  int res_9_orig = sprintf(str_orig, "%-5ld", d);
  ck_assert_int_eq(res_9, res_9_orig);
  ck_assert_str_eq(str, str_orig);

  int res_10 = s21_sprintf(str, "%+5ld", d);
  int res_10_orig = sprintf(str_orig, "%+5ld", d);
  ck_assert_int_eq(res_10, res_10_orig);
  ck_assert_str_eq(str, str_orig);

  int res_11 = s21_sprintf(str, "% 5ld", d);
  int res_11_orig = sprintf(str_orig, "% 5ld", d);
  ck_assert_int_eq(res_11, res_11_orig);
  ck_assert_str_eq(str, str_orig);

  int res_12 = s21_sprintf(str, "%.5ld", d);
  int res_12_orig = sprintf(str_orig, "%.5ld", d);
  ck_assert_int_eq(res_12, res_12_orig);
  ck_assert_str_eq(str, str_orig);
}
END_TEST

START_TEST(sprintf_u_test) {
  char str[80] = {'\0'};
  char str_orig[80] = {'\0'};
  unsigned int u = 228;

  int res_1 = s21_sprintf(str, "%10.5u", u);
  int res_1_orig = sprintf(str_orig, "%10.5u", u);
  ck_assert_int_eq(res_1, res_1_orig);
  ck_assert_str_eq(str, str_orig);

  int res_2 = s21_sprintf(str, "%-10.5u", u);
  int res_2_orig = sprintf(str_orig, "%-10.5u", u);
  ck_assert_int_eq(res_2, res_2_orig);
  ck_assert_str_eq(str, str_orig);

  int res_3 = s21_sprintf(str, "%3.5u", u);
  int res_3_orig = sprintf(str_orig, "%3.5u", u);
  ck_assert_int_eq(res_3, res_3_orig);
  ck_assert_str_eq(str, str_orig);

  int res_4 = s21_sprintf(str, "%u", u);
  int res_4_orig = sprintf(str_orig, "%u", u);
  ck_assert_int_eq(res_4, res_4_orig);
  ck_assert_str_eq(str, str_orig);

  int res_5 = s21_sprintf(str, "%u", u);
  int res_5_orig = sprintf(str_orig, "%u", u);
  ck_assert_int_eq(res_5, res_5_orig);
  ck_assert_str_eq(str, str_orig);

  int res_6 = s21_sprintf(str, "%5u", u);
  int res_6_orig = sprintf(str_orig, "%5u", u);
  ck_assert_int_eq(res_6, res_6_orig);
  ck_assert_str_eq(str, str_orig);

  int res_7 = s21_sprintf(str, "%-5u", u);
  int res_7_orig = sprintf(str_orig, "%-5u", u);
  ck_assert_int_eq(res_7, res_7_orig);
  ck_assert_str_eq(str, str_orig);

  int res_8 = s21_sprintf(str, "%10.5u", u);
  int res_8_orig = sprintf(str_orig, "%10.5u", u);
  ck_assert_int_eq(res_8, res_8_orig);
  ck_assert_str_eq(str, str_orig);

  int res_9 = s21_sprintf(str, "%.5u", u);
  int res_9_orig = sprintf(str_orig, "%.5u", u);
  ck_assert_int_eq(res_9, res_9_orig);
  ck_assert_str_eq(str, str_orig);
}
END_TEST

START_TEST(test_proc) {
  char buf1[100];
  char buf2[100];
  sprintf(buf1, "%%");
  s21_sprintf(buf2, "%%");
  ck_assert_str_eq(buf1, buf2);

  // Простые тесты
}
END_TEST

START_TEST(test_simple) {
  char buf2[100];
  char buf3[100];
  char buf4[100];
  char buf5[100];
  char buf6[100];
  char buf7[100];
  char buf8[100];
  char buf9[100];
  char buf10[100];
  char buf11[100];

  char buf2_[100];
  char buf3_[100];
  char buf4_[100];
  char buf5_[100];
  char buf6_[100];
  char buf7_[100];
  char buf8_[100];
  char buf9_[100];
  char buf10_[100];
  char buf11_[100];

  sprintf(buf2, "%g", 0.000000001);
  s21_sprintf(buf2_, "%g", 0.000000001);
  sprintf(buf3, "%G", 0.000000001);
  s21_sprintf(buf3_, "%G", 0.000000001);
  sprintf(buf4, "%e", 123456789.123456789);
  s21_sprintf(buf4_, "%e", 123456789.123456789);
  sprintf(buf5, "%E", 123456789.123456789);
  s21_sprintf(buf5_, "%E", 123456789.123456789);
  sprintf(buf6, "%x", 0xabcdef);
  s21_sprintf(buf6_, "%x", 0xabcdef);
  sprintf(buf7, "%X", 0xABCDEF);
  s21_sprintf(buf7_, "%X", 0xABCDEF);
  sprintf(buf8, "%x", 0xABCDEF);
  s21_sprintf(buf8_, "%x", 0xABCDEF);
  sprintf(buf9, "%X", 0xabcdef);
  s21_sprintf(buf9_, "%X", 0xabcdef);
  sprintf(buf10, "%o", 20);
  s21_sprintf(buf10_, "%o", 20);

  double number = 123456789.123456789;
  void *ptr_1 = &number;
  void *ptr_2 = &number;
  sprintf(buf11, "%p", ptr_1);
  s21_sprintf(buf11_, "%p", ptr_2);

  ck_assert_str_eq(buf2, buf2_);
  ck_assert_str_eq(buf3, buf3_);
  ck_assert_str_eq(buf4, buf4_);
  ck_assert_str_eq(buf5, buf5_);
  ck_assert_str_eq(buf6, buf6_);
  ck_assert_str_eq(buf7, buf7_);
  ck_assert_str_eq(buf8, buf8_);
  ck_assert_str_eq(buf9, buf9_);
  ck_assert_str_eq(buf10, buf10_);
  ck_assert_str_eq(buf11, buf11_);
}
END_TEST

START_TEST(test_complex_e) {
  char buf1[100];
  char buf2[100];
  char buf3[100];
  char buf4[100];
  char buf1_[100];
  char buf2_[100];
  char buf3_[100];
  char buf4_[100];
  sprintf(buf1, "%*.e", 10, 123456789.123456789);
  s21_sprintf(buf1_, "%*.e", 10, 123456789.123456789);
  sprintf(buf2, "%.*e", 5, 123456789.123456789);
  s21_sprintf(buf2_, "%.*e", 5, 123456789.123456789);
  sprintf(buf3, "%*.*e", 10, 5, 123456789.123456789);
  s21_sprintf(buf3_, "%*.*e", 10, 5, 123456789.123456789);
  sprintf(buf4, "%020e", 123456789.123456789);
  s21_sprintf(buf4_, "%020e", 123456789.123456789);
  ck_assert_str_eq(buf1, buf1_);
  ck_assert_str_eq(buf2, buf2_);
  ck_assert_str_eq(buf3, buf3_);
  ck_assert_str_eq(buf4, buf4_);
}
END_TEST

START_TEST(test_complex_E) {
  char buf1[100];
  char buf2[100];
  char buf3[100];
  char buf4[100];
  char buf1_[100];
  char buf2_[100];
  char buf3_[100];
  char buf4_[100];
  sprintf(buf1, "%*.E", 10, 123456789.123456789);
  s21_sprintf(buf1_, "%*.E", 10, 123456789.123456789);
  sprintf(buf2, "%.*E", 5, 123456789.123456789);
  s21_sprintf(buf2_, "%.*E", 5, 123456789.123456789);
  sprintf(buf3, "%*.*E", 10, 5, 123456789.123456789);
  s21_sprintf(buf3_, "%*.*E", 10, 5, 123456789.123456789);
  sprintf(buf4, "%020E", 123456789.123456789);
  s21_sprintf(buf4_, "%020E", 123456789.123456789);
  ck_assert_str_eq(buf1, buf1_);
  ck_assert_str_eq(buf2, buf2_);
  ck_assert_str_eq(buf3, buf3_);
  ck_assert_str_eq(buf4, buf4_);
}
END_TEST

START_TEST(test_complex_x) {
  char buf1[100];
  char buf2[100];
  char buf3[100];
  char buf4[100];
  char buf5[100];
  char buf6[100];
  char buf1_[100];
  char buf2_[100];
  char buf3_[100];
  char buf4_[100];
  char buf5_[100];
  char buf6_[100];
  sprintf(buf1, "%*.x", 10, 0xabcdef);
  s21_sprintf(buf1_, "%*.x", 10, 0xabcdef);
  sprintf(buf2, "%.*x", 5, 0xabcdef);
  s21_sprintf(buf2_, "%.*x", 5, 0xabcdef);
  sprintf(buf3, "%*.*x", 10, 5, 0xabcdef);
  s21_sprintf(buf3_, "%*.*x", 10, 5, 0xabcdef);
  sprintf(buf4, "%020x", 0xabcdef);
  s21_sprintf(buf4_, "%020x", 0xabcdef);
  sprintf(buf5, "%#x", 0xabcdef);
  s21_sprintf(buf5_, "%#x", 0xabcdef);
  sprintf(buf6, "%#x", 0XABCDEF);
  s21_sprintf(buf6_, "%#x", 0XABCDEF);
  ck_assert_str_eq(buf1, buf1_);
  ck_assert_str_eq(buf2, buf2_);
  ck_assert_str_eq(buf3, buf3_);
  ck_assert_str_eq(buf4, buf4_);
  ck_assert_str_eq(buf5, buf5_);
  ck_assert_str_eq(buf6, buf6_);
}
END_TEST

START_TEST(test_complex_X) {
  char buf1[100];
  char buf2[100];
  char buf3[100];
  char buf4[100];
  char buf5[100];
  char buf6[100];
  char buf1_[100];
  char buf2_[100];
  char buf3_[100];
  char buf4_[100];
  char buf5_[100];
  char buf6_[100];
  sprintf(buf1, "%*.X", 10, 0XABCDEF);
  s21_sprintf(buf1_, "%*.X", 10, 0XABCDEF);
  sprintf(buf2, "%.*X", 5, 0XABCDEF);
  s21_sprintf(buf2_, "%.*X", 5, 0XABCDEF);
  sprintf(buf3, "%*.*X", 10, 5, 0XABCDEF);
  s21_sprintf(buf3_, "%*.*X", 10, 5, 0XABCDEF);
  sprintf(buf4, "%020X", 0XABCDEF);
  s21_sprintf(buf4_, "%020X", 0XABCDEF);
  sprintf(buf5, "%#X", 0XABCDEF);
  s21_sprintf(buf5_, "%#X", 0XABCDEF);
  sprintf(buf6, "%#X", 0xabcdef);
  s21_sprintf(buf6_, "%#X", 0xabcdef);
  ck_assert_str_eq(buf1, buf1_);
  ck_assert_str_eq(buf2, buf2_);
  ck_assert_str_eq(buf3, buf3_);
  ck_assert_str_eq(buf4, buf4_);
  ck_assert_str_eq(buf5, buf5_);
  ck_assert_str_eq(buf6, buf6_);
}
END_TEST

START_TEST(test_complex_o) {
  char buf1[100];
  char buf2[100];
  char buf3[100];
  char buf4[100];
  char buf5[100];
  char buf1_[100];
  char buf2_[100];
  char buf3_[100];
  char buf4_[100];
  char buf5_[100];
  sprintf(buf1, "%*.o", 10, 20);
  s21_sprintf(buf1_, "%*.o", 10, 20);
  sprintf(buf2, "%.*o", 5, 20);
  s21_sprintf(buf2_, "%.*o", 5, 20);
  sprintf(buf3, "%*.*o", 10, 5, 20);
  s21_sprintf(buf3_, "%*.*o", 10, 5, 20);
  sprintf(buf4, "%020o", 20);
  s21_sprintf(buf4_, "%020o", 20);
  sprintf(buf5, "%#o", 20);
  s21_sprintf(buf5_, "%#o", 20);
  ck_assert_str_eq(buf1, buf1_);
  ck_assert_str_eq(buf2, buf2_);
  ck_assert_str_eq(buf3, buf3_);
  ck_assert_str_eq(buf4, buf4_);
  ck_assert_str_eq(buf5, buf5_);
}
END_TEST

START_TEST(test_anomal_large_int) {
  char buf1[100];
  char buf1_[100];
  sprintf(buf1, "%ld", 1234567890000001);
  s21_sprintf(buf1_, "%ld", 1234567890000001);
  ck_assert_str_eq(buf1, buf1_);
}
END_TEST

START_TEST(test_precision) {
  double number = 127.9991;
  char buf1[100];
  char buf2[100];

  char buf4[100];
  char buf5[100];
  char buf6[100];
  char buf7[100];
  char buf1_[100];
  char buf2_[100];

  char buf4_[100];
  char buf5_[100];
  char buf6_[100];
  char buf7_[100];
  sprintf(buf1, "%.*f", 3, number);
  s21_sprintf(buf1_, "%.*f", 3, number);
  sprintf(buf2, "%.*g", 3, number);
  s21_sprintf(buf2_, "%.*g", 3, number);
  sprintf(buf4, "%.*f", 0, number);
  s21_sprintf(buf4_, "%.*f", 0, number);

  number = 127.1991;
  sprintf(buf5, "%.*f", 0, number);
  s21_sprintf(buf5_, "%.*f", 0, number);
  sprintf(buf6, "%.*e", 3, number);
  s21_sprintf(buf6_, "%.*e", 3, number);
  sprintf(buf7, "%.*e", 0, number);
  s21_sprintf(buf7_, "%.*e", 0, number);
  ck_assert_str_eq(buf1, buf1_);
  ck_assert_str_eq(buf2, buf2_);

  ck_assert_str_eq(buf4, buf4_);
  ck_assert_str_eq(buf5, buf5_);
  ck_assert_str_eq(buf6, buf6_);
  ck_assert_str_eq(buf7, buf7_);
}
END_TEST

START_TEST(test_large_int) {
  long int number = 1234567890000000001LL;
  char buf1[100];
  char buf1_[100];
  sprintf(buf1, "%ld", number);
  s21_sprintf(buf1_, "%ld", number);
  ck_assert_str_eq(buf1, buf1_);
}
END_TEST

START_TEST(test_hash_e) {
  double number = 0.8;
  char buf1[100];
  char buf1_[100];
  char buf2[100];
  char buf2_[100];
  sprintf(buf1, "%#e", number);
  s21_sprintf(buf1_, "%#e", number);
  sprintf(buf2, "%#e", 0.0);
  s21_sprintf(buf2_, "%#e", 0.0);
  ck_assert_str_eq(buf1, buf1_);
  ck_assert_str_eq(buf2, buf2_);
}
END_TEST

START_TEST(test_zero_padding) {
  double number = 0.8;
  char buf1[100];
  char buf2[100];
  char buf3[100];
  char buf4[100];
  char buf5[100];
  char buf6[100];
  char buf7[100];
  char buf8[100];
  char buf9[100];
  char buf1_[100];
  char buf2_[100];
  char buf3_[100];
  char buf4_[100];
  char buf5_[100];
  char buf6_[100];
  char buf7_[100];
  char buf8_[100];
  char buf9_[100];
  sprintf(buf1, "%08e", number);
  s21_sprintf(buf1_, "%08e", number);
  sprintf(buf2, "%08f", number);
  s21_sprintf(buf2_, "%08f", number);
  sprintf(buf3, "%08f", 9.1);
  s21_sprintf(buf3_, "%08f", 9.1);
  sprintf(buf4, "%08g", number);
  s21_sprintf(buf4_, "%08g", number);
  sprintf(buf5, "%023g", number);
  s21_sprintf(buf5_, "%023g", number);
  sprintf(buf6, "%08G", number);
  s21_sprintf(buf6_, "%08G", number);
  sprintf(buf7, "%023G", number);
  s21_sprintf(buf7_, "%023G", number);
  sprintf(buf8, "%08d", 10);
  s21_sprintf(buf8_, "%08d", 10);
  sprintf(buf9, "%023d", 10);
  s21_sprintf(buf9_, "%023d", 10);
  ck_assert_str_eq(buf1, buf1_);
  ck_assert_str_eq(buf2, buf2_);
  ck_assert_str_eq(buf3, buf3_);
  ck_assert_str_eq(buf4, buf4_);
  ck_assert_str_eq(buf5, buf5_);
  ck_assert_str_eq(buf6, buf6_);
  ck_assert_str_eq(buf7, buf7_);
  ck_assert_str_eq(buf8, buf8_);
  ck_assert_str_eq(buf9, buf9_);
}
END_TEST

START_TEST(test_mixed_ld) {
  long int number = 1234567890000000001LL;
  char buf1[100];
  char buf2[100];
  char buf1_[100];
  char buf2_[100];
  sprintf(buf1, "%*.*ld", 5, 8, number);
  s21_sprintf(buf1_, "%*.*ld", 5, 8, number);
  sprintf(buf2, "%*.*ld", 5, 10, number);
  s21_sprintf(buf2_, "%*.*ld", 5, 10, number);
  ck_assert_str_eq(buf1, buf1_);
  ck_assert_str_eq(buf2, buf2_);
}
END_TEST

START_TEST(test_mixed_f) {
  double num = 12000.9;
  char buf1[100];
  char buf2[100];
  char buf1_[100];
  char buf2_[100];
  sprintf(buf1, "%0#*.*f", 10, 1, num);
  s21_sprintf(buf1_, "%0#*.*f", 10, 1, num);
  sprintf(buf2, "%0#*.*f", 10, 14, num);
  s21_sprintf(buf2_, "%0#*.*f", 10, 14, num);
  ck_assert_str_eq(buf1, buf1_);
  ck_assert_str_eq(buf2, buf2_);
}
END_TEST

START_TEST(test_mixed_e) {
  double num = 12000.9;
  char buf1[100];
  char buf1_[100];
  sprintf(buf1, "%0#*.*e", 10, 14, num);
  s21_sprintf(buf1_, "%0#*.*e", 10, 14, num);
  ck_assert_str_eq(buf1, buf1_);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, memchr_test);
  tcase_add_test(tc1_1, memcmp_test);
  tcase_add_test(tc1_1, memcpy_test);
  tcase_add_test(tc1_1, memset_test);
  tcase_add_test(tc1_1, strncat_test);
  tcase_add_test(tc1_1, strchr_test);
  tcase_add_test(tc1_1, strncmp_test);
  tcase_add_test(tc1_1, strncpy_test);
  tcase_add_test(tc1_1, strcspn_test);
  tcase_add_test(tc1_1, strlen_test);
  tcase_add_test(tc1_1, strpbrk_test);
  tcase_add_test(tc1_1, strrchr_test);
  tcase_add_test(tc1_1, strstr_test);
  tcase_add_test(tc1_1, strtok_test);
  tcase_add_test(tc1_1, sprintf_d_test);
  tcase_add_test(tc1_1, sprintf_c_test);
  tcase_add_test(tc1_1, sprintf_s_test);
  tcase_add_test(tc1_1, sprintf_ld_test);
  tcase_add_test(tc1_1, sprintf_u_test);
  tcase_add_test(tc1_1, test_proc);
  tcase_add_test(tc1_1, test_simple);
  tcase_add_test(tc1_1, test_complex_e);
  tcase_add_test(tc1_1, test_complex_E);
  tcase_add_test(tc1_1, test_complex_x);
  tcase_add_test(tc1_1, test_complex_X);
  tcase_add_test(tc1_1, test_complex_o);
  tcase_add_test(tc1_1, test_anomal_large_int);
  tcase_add_test(tc1_1, test_precision);
  tcase_add_test(tc1_1, test_large_int);
  tcase_add_test(tc1_1, test_hash_e);
  tcase_add_test(tc1_1, test_zero_padding);
  tcase_add_test(tc1_1, test_mixed_ld);
  tcase_add_test(tc1_1, test_mixed_f);
  tcase_add_test(tc1_1, test_mixed_e);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
